### ISSUE TITLE
Allow negative balances

### ISSUE THREAD

**Issue by garious** [loomprotocol/silk#43]
Some interesting possibilities when balances are allowed to go negative:

* Loans
* Fast parallel verification of the ledger (divide and conquer and no need for bigint)

Downsides:

* Will frequently need to check for positive numbers throughout the codebase
* Max tokens cut in half

Seems the pros far outweigh the cons. Ears open if others would care to comment.

**Comment by aeyakovenko** [comment]
so this would be a per "token" specification, no?

**Comment by garious** [comment]
Not sure I understand the question. Balances are tied to Public Keys.

**Comment by aeyakovenko** [comment]
if we had custom user tokens, some may be of unsigned type, some maybe signed
